### ISSUE TITLE
[BUG] CXHub won't load.

### ISSUE THREAD

**Issue by focat69** [Code1Tech/celestalx#1]
I am working on a fix.

**Comment by Code1Tech** [comment]
This happened about 3 hours ago, I just recently fixed it.

**_TIP FOR FUTURE: Pres "Insert/Ins" on keyboard with S^X and inspect with S^X console, not dev console._**

**Comment by Code1Tech** [comment]
TIP 2: **EXECUTE IN S^X INTERAL NOT ACTUAL EXECUTOR TO DEBUG**
